version: "3"
services:

  his-activemq:
    image: rmohr/activemq
    restart: always
    ports:
      - "61616:61616"
      - "8161:8161"

  graphite:
    image: hopsoft/graphite-statsd
    restart: always
    ports:
      - "8000:80"
      - "2003:2003"
      - "2004:2004"
      - "2023:2023"
      - "2024:2024"
      - "8125:8125/udp"
      - "8126:8126"
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    links:
      - graphite
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - ./grafana/data:/var/lib/grafana

  his_start_his-config:
        image: bash
        depends_on:
          - his-config
        command: >
          /usr/local/bin/bash -c "
            while ! nc -z his-config 17601;
            do
              echo sleeping;
              sleep 1;
            done;
            echo Connected!;
          "

  his-config:
      image: isaacguo/his-config
      restart: always
      ports:
        - "17601:17601"
      command: --spring.profiles.active=production

  his-eureka:
    image: isaacguo/his-eureka
    restart: always
    ports:
      - "8761:8761"
    depends_on:
      - his-config
    command: --spring.profiles.active=production


  his-employee:
    image: isaacguo/his-employee
    restart: always
    ports:
      - "8091:8080"
    depends_on:
      - his-config
      - his-eureka
    command: --spring.profiles.active=production

  his-treatment:
    image: isaacguo/his-treatment
    restart: always
    ports:
      - "8092:8080"
    depends_on:
      - his-config
      - his-eureka
    command: --spring.profiles.active=production

  his-medicine:
    image: isaacguo/his-medicine
    restart: always
    ports:
      - "8095:8080"
    depends_on:
      - his-config
      - his-eureka
    command: --spring.profiles.active=production

  his-procurement:
    image: isaacguo/his-procurement
    restart: always
    ports:
      - "8096:8080"
    depends_on:
      - his-config
      - his-eureka
    command: --spring.profiles.active=production

  his-gateway:
    image: isaacguo/his-gateway
    restart: always
    ports:
      - "8090:8080"
    depends_on:
      - his-config
      - his-eureka
      - his-employee
      - his-medicine
    command: --spring.profiles.active=production

