version: "3"
services:

  his-activemq:
    image: rmohr/activemq
    ports:
      - "61616:61616"
      - "8161:8161"

  his_start_his-config:
        image: bash
        depends_on:
          - his-config
          - his-db
        command: >
          /usr/local/bin/bash -c "
            while ! nc -z his-config 17601;
            do
              echo sleeping;
              sleep 1;
            done;
            echo Connected!;
          "

  his-config:
    image: isaacguo/his-config
    ports:
      - "17601:17601"
    command: --spring.profiles.active=production

  his-db:
    image: isaacguo/mysql-5-utf8
    environment:
      MYSQL_ROOT_PASSWORD: His_Solution_p4ssw0rd
    volumes:
      - his-db-volume:/var/lib/mysql

  his-eureka:
    image: isaacguo/his-eureka
    ports:
      - "8761:8761"
    depends_on:
      - his-config
    command: --spring.profiles.active=production

  his-employee:
    image: isaacguo/his-employee
    ports:
      - "8091:8080"
    depends_on:
      - his-config
      - his-eureka
      - his-db
    command: --spring.profiles.active=production
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  his-treatment:
    image: isaacguo/his-treatment
    ports:
      - "8092:8080"
    depends_on:
      - his-config
      - his-eureka
      - his-db
    command: --spring.profiles.active=production
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"


  his-medicine:
    image: isaacguo/his-medicine
    ports:
      - "8095:8080"
    depends_on:
      - his-config
      - his-eureka
      - his-db
    command: --spring.profiles.active=production
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  his-procurement:
    image: isaacguo/his-procurement
    ports:
      - "8096:8080"
    depends_on:
      - his-config
      - his-eureka
      - his-db
    command: --spring.profiles.active=production
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"



  his-medical-test:
    image: isaacguo/his-medical-test
    ports:
      - "8097:8080"
    depends_on:
      - his-config
      - his-eureka
      - his-db
    command: --spring.profiles.active=production
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"


  his-finance:
    image: isaacguo/his-finance
    ports:
      - "8098:8080"
    depends_on:
      - his-config
      - his-eureka
      - his-db
    command: --spring.profiles.active=production
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  his-gateway:
    image: isaacguo/his-gateway
    ports:
      - "8090:8080"
    depends_on:
      - his-config
      - his-eureka
      - his-employee
      - his-medicine
      - his-db
    command: --spring.profiles.active=production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/root/his-backup:/his-backup"

volumes:
   his-db-volume:
