export enum TreatmentCaseStatusEnum{

  BOOKED="BOOKED",
  UNPAID="UNPAID",
  UNPRESENTED="UNPRESENTED",
  WAITING="WAITING",
  CURING="CURING",
  CALLED="CALLED",
  FINISHED="FINISHED",
  UNFINISHED="UNFINISHED"
}
