create table application_user (id bigint not null auto_increment, password varchar(255), username varchar(255), primary key (id)) ENGINE=InnoDB;
create table authorization_assignment_entity (id bigint not null auto_increment, authorization_id bigint, topic_id bigint, primary key (id)) ENGINE=InnoDB;
create table authorization_assignment_entity_allowed_operations (authorization_assignment_entity_id bigint not null, allowed_operations_id bigint not null) ENGINE=InnoDB;
create table authorization_entity (id bigint not null auto_increment, uid bigint, user_account varchar(255), username varchar(255), primary key (id)) ENGINE=InnoDB;
create table authorization_topic_entity (id bigint not null auto_increment, name varchar(255), primary key (id)) ENGINE=InnoDB;
create table department_entity (id bigint not null auto_increment, description varchar(255), expose_to_public bit not null, name varchar(255), uuid varchar(255), primary key (id)) ENGINE=InnoDB;
create table employee_entity (id bigint not null auto_increment, login_account varchar(255), name varchar(255), self_introduction varchar(255), uuid binary(255), department_id bigint, employee_type_id bigint, primary key (id)) ENGINE=InnoDB;
create table employee_type_entity (id bigint not null auto_increment, name varchar(255), primary key (id)) ENGINE=InnoDB;
create table expense_entity (id bigint not null auto_increment, pet_owner_id bigint, primary key (id)) ENGINE=InnoDB;
create table pet_entity (id bigint not null auto_increment, age integer not null, color integer, date_of_birth datetime, gender integer, name varchar(255), sterilized bit not null, uuid binary(255), pet_owner_id bigint, pet_type_id bigint, primary key (id)) ENGINE=InnoDB;
create table pet_owner_entity (id bigint not null auto_increment, address varchar(255), cell_phone varchar(255), date_of_birth datetime, email varchar(255), gender integer, home_phone varchar(255), member_number varchar(255), name varchar(255), uuid varchar(255), primary key (id)) ENGINE=InnoDB;
create table pet_type_entity (id bigint not null auto_increment, is_root bit not null, name varchar(255), parent_id bigint, primary key (id)) ENGINE=InnoDB;
create table registration_entity (id bigint not null auto_increment, book_date datetime, created_date datetime, index_of_day integer not null, price bigint, registration_status integer, doctor_id bigint, operator_id bigint, pet_id bigint, primary key (id)) ENGINE=InnoDB;
create table registration_number_entity (id bigint not null auto_increment, date date, number integer, doctor_id bigint, primary key (id)) ENGINE=InnoDB;
create table topic_operation_entity (id bigint not null auto_increment, name varchar(255), authorization_topic_id bigint, primary key (id)) ENGINE=InnoDB;
create table topic_operation_entity_authorization_assignment_list (topic_operation_entity_id bigint not null, authorization_assignment_list_id bigint not null) ENGINE=InnoDB;
create table treatment_case_entity (id bigint not null auto_increment, create_result bit not null, created_date datetime, treatment_case_status varchar(255), treatment_date datetime, uuid varchar(255), department_id bigint, doctor_id bigint, pet_id bigint, pet_owner_id bigint, primary key (id)) ENGINE=InnoDB;
alter table authorization_assignment_entity add constraint FKedjwiuan814a19bi4yy07tdph foreign key (authorization_id) references authorization_entity (id);
alter table authorization_assignment_entity add constraint FK8dqq1kc7jp0clkstctpnjtl2y foreign key (topic_id) references authorization_topic_entity (id);
alter table authorization_assignment_entity_allowed_operations add constraint FK5vwid8n1jmi0r5h2fxxnbvbgn foreign key (allowed_operations_id) references topic_operation_entity (id);
alter table authorization_assignment_entity_allowed_operations add constraint FKngkgigjkrhs9p2ir6bh9cuu6a foreign key (authorization_assignment_entity_id) references authorization_assignment_entity (id);
alter table employee_entity add constraint FKrj4v5xw1jix23uajsogqdy0a0 foreign key (department_id) references department_entity (id);
alter table employee_entity add constraint FKkve3m2lulwm1xav7ik2bowhr6 foreign key (employee_type_id) references employee_type_entity (id);
alter table expense_entity add constraint FKt30kehjp5r3scxf5xt2l2lc99 foreign key (pet_owner_id) references pet_owner_entity (id);
alter table pet_entity add constraint FKhpcc8jomtw8h2hfqb247m0dq6 foreign key (pet_owner_id) references pet_owner_entity (id);
alter table pet_entity add constraint FKaof55hsdpkgy8n1o1bwi8v28t foreign key (pet_type_id) references pet_type_entity (id);
alter table pet_type_entity add constraint FKrfo06j1yysq5g1l9nywwa95a7 foreign key (parent_id) references pet_type_entity (id);
alter table registration_entity add constraint FK3dalsjnwcaaue8nysr0gd1gs7 foreign key (doctor_id) references employee_entity (id);
alter table registration_entity add constraint FKdcnt0v441e7q3s1b2psr4m7av foreign key (operator_id) references employee_entity (id);
alter table registration_entity add constraint FK6pfh5xcvgwluplcdh0ch1sivf foreign key (pet_id) references pet_entity (id);
alter table registration_number_entity add constraint FKo8r0g185lhfwqou89casipody foreign key (doctor_id) references employee_entity (id);
alter table topic_operation_entity add constraint FKoec3nr2ausdy7u53qubpxopo8 foreign key (authorization_topic_id) references authorization_topic_entity (id);
alter table topic_operation_entity_authorization_assignment_list add constraint FKtmjvf3170d9xr73l2i2sy705t foreign key (authorization_assignment_list_id) references authorization_assignment_entity (id);
alter table topic_operation_entity_authorization_assignment_list add constraint FK4y6aqtertcn95oyqdiba3jdbf foreign key (topic_operation_entity_id) references topic_operation_entity (id);
alter table treatment_case_entity add constraint FKgau0hin3ms4oooht1l898a4cb foreign key (department_id) references department_entity (id);
alter table treatment_case_entity add constraint FK66k2f9imb7mfetn3habawq81b foreign key (doctor_id) references employee_entity (id);
alter table treatment_case_entity add constraint FKp7mrx9givae5w86lcv6fty4cl foreign key (pet_id) references pet_entity (id);
alter table treatment_case_entity add constraint FK2ihoeg1wimgbb2rkkobw3sujk foreign key (pet_owner_id) references pet_owner_entity (id);
